{ lib
, buildPythonPackage
, fetchFromGitHub 
, click
, numpy
, openpyxl
, pandas
, pypdf2
, tabula-py
}:

buildPythonPackage rec {
  pname = "Pdf2TimeTable";
  version = "1.0.0";

  src = fetchFromGitHub {
    owner = "SCOTT-HAMILTON";
    repo = "Pdf2TimeTable";
    rev = "5efd9479115197544c736f1cefaf7a9f3b6a6cce";
    sha256 = "19bhai2gmri6553km7l51anw18x9b439aii3rv2chs6sp52d18m1";
  };

  # src = ./src.tar.gz;

  propagatedBuildInputs = [
    click
    numpy
    pandas
    pypdf2
    openpyxl
    tabula-py
  ];

  doCheck = false;

  meta = with lib; {
    description = "Converts a pdf timetable (generated by pronote) to an excel timetable (that can be used with TimeTable2Header)";
    license = licenses.mit;
    maintainers = [ "Scott Hamilton <sgn.hamilton+nixpkgs@protonmail.com>" ];
    platforms = platforms.linux;
  };
}
