{ lib
, buildPythonPackage
, fetchFromGitHub 
, click
, numpy
, openpyxl
, pandas
, pypdf2
, tabula-py
}:

buildPythonPackage rec {
  pname = "Pdf2TimeTable";
  version = "1.0.0";

  src = fetchFromGitHub {
    owner = "SCOTT-HAMILTON";
    repo = "Pdf2TimeTable";
    rev = "4e5cc879d584916933ca72c93b68b076a1bcffbd";
    sha256 = "16mvsbzbyh6l18jdmdlqwir34scnpysnkkazz2dqngic9s1zg6kw";
  };

  # src = ./src.tar.gz;

  propagatedBuildInputs = [
    click
    numpy
    pandas
    pypdf2
    openpyxl
    tabula-py
  ];

  doCheck = false;

  meta = with lib; {
    description = "Converts a pdf timetable (generated by pronote) to an excel timetable (that can be used with TimeTable2Header)";
    license = licenses.mit;
    maintainers = [ "Scott Hamilton <sgn.hamilton+nixpkgs@protonmail.com>" ];
    platforms = platforms.linux;
  };
}
