# This file has been generated by node2nix 1.9.0. Do not edit!

{ nixosVersion
, pkgs ? import <nixpkgs> {
    inherit system;
},
system ? builtins.currentSystem,
nodejs ? pkgs."nodejs-14_x"
}:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv lib python2 runCommand writeTextFile writeShellScript;
    inherit pkgs nodejs;
    libtool = if pkgs.stdenv.isDarwin then pkgs.darwin.cctools else null;
  };
  src = pkgs.fetchFromGitHub {
    owner = "SCOTT-HAMILTON";
    repo = "tfk-api-unoconv";
    rev = "a2f29e71d12fa9fb3ddbf1b67ab0293bdcf3e64c";
    sha256 = "1vdf34ckghhjnih54krsq6r9vj8lavxs48lbb5s5pvzcgylxfqmk";
  };
in
(import ./node-packages.nix {
  inherit (pkgs) fetchurl nix-gitignore stdenv lib fetchgit;
  inherit nodeEnv src;
}).package.overrideAttrs (old: {
  postInstall = ''
    mkdir -p "$out/bin"
    substituteInPlace "$out/lib/node_modules/tfk-api-unoconv/standalone.js" \
      --replace '/usr/bin/env node' '${nodejs}/bin/node'
    chmod +x "$out/lib/node_modules/tfk-api-unoconv/standalone.js"
    ln -s "$out/lib/node_modules/tfk-api-unoconv/standalone.js" "$out/bin/tfk-api-unoconv"
  '';
})


