# This file has been generated by node2nix 1.8.0. Do not edit!

{pkgs ? import <nixpkgs> {
    inherit system;
  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-12_x"}:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv python2 utillinux runCommand writeTextFile;
    inherit nodejs;
    libtool = if pkgs.stdenv.isDarwin then pkgs.darwin.cctools else null;
  };
  src = pkgs.fetchFromGitHub {
    owner = "SCOTT-HAMILTON";
    repo = "pronote-timetable-fetch";
    rev = "9767abb2e8b5ecac0f99944ebe3a4057f7912d25";
    sha256 = "0rs73ga4ijjn6wh2f5m4sb9y7fza004859vf4nic9wi6hp76v9pn";
  };
in
(import ./node-packages.nix {
  inherit (pkgs) fetchurl;
  inherit nodeEnv src;
}).package
