# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, fetchFromGitHub, globalBuildInputs ? [], gitignoreSource}:

let
  sources = {
    "@braintree/sanitize-url-3.1.0" = {
      name = "_at_braintree_slash_sanitize-url";
      packageName = "@braintree/sanitize-url";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@braintree/sanitize-url/-/sanitize-url-3.1.0.tgz";
        sha512 = "GcIY79elgB+azP74j8vqkiXz8xLFfIzbQJdlwOPisgbKT00tviJQuEghOXSMVxJ00HoYJbGswr4kcllUc4xCcg==";
      };
    };
    "@types/node-14.14.37" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "14.14.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-14.14.37.tgz";
        sha512 = "XYmBiy+ohOR4Lh5jE379fV2IU+6Jn4g5qASinhitfyO71b/sCo6MKsMLF5tc7Zf2CE8hViVQyYSobJNke8OvUw==";
      };
    };
    "@types/yauzl-2.9.1" = {
      name = "_at_types_slash_yauzl";
      packageName = "@types/yauzl";
      version = "2.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/yauzl/-/yauzl-2.9.1.tgz";
        sha512 = "A1b8SU4D10uoPjwb0lnHmmu8wZhR9d+9o2PKBQT2jU5YPTKsxac6M2qGAdY7VcL+dHHhARVUDmeg0rOrcd9EjA==";
      };
    };
    "agent-base-6.0.2" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-6.0.2.tgz";
        sha512 = "RZNwNclF7+MS/8bDg70amg32dyeZGZxiDuQmZxKLAlQjr3jGyLx+4Kkk58UO7D2QdgFIQCovuSuZESne6RG6XQ==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "bl-4.1.0" = {
      name = "bl";
      packageName = "bl";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-4.1.0.tgz";
        sha512 = "1W07cM9gS6DcLperZfFSj+bWLtaPGSOHWhPiGzXmvVJbRLdG82sH/Kn8EtW1VqWVA54AKf2h5k5BbnIbwF3h6w==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "buffer-5.7.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.7.1.tgz";
        sha512 = "EHcyIPBQ4BSGlvjB16k5KgAJ27CIsHY/2JBmCRReo48y9rQ3MaUzWX3KVlBa4U7MyX02HdVj0K7C3WaB3ju7FQ==";
      };
    };
    "buffer-crc32-0.2.13" = {
      name = "buffer-crc32";
      packageName = "buffer-crc32";
      version = "0.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.13.tgz";
        sha1 = "0d333e3f00eac50aa1454abd30ef8c2a5d9a7242";
      };
    };
    "buffer-from-1.1.1" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.1.tgz";
        sha512 = "MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==";
      };
    };
    "camel-case-3.0.0" = {
      name = "camel-case";
      packageName = "camel-case";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camel-case/-/camel-case-3.0.0.tgz";
        sha1 = "ca3c3688a4e9cf3a4cda777dc4dcbc713249cf73";
      };
    };
    "chalk-4.1.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.0.tgz";
        sha512 = "qwx12AxXe2Q5xQ43Ac//I6v5aXTipYrSESdOgzrN+9XjgEpyjpKuvSGaN4qE93f7TQTlerQQ8S+EQ0EyDoVL1A==";
      };
    };
    "chownr-1.1.4" = {
      name = "chownr";
      packageName = "chownr";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/chownr/-/chownr-1.1.4.tgz";
        sha512 = "jJ0bqzaylmJtVnNgzTeSOs8DPavpbYgEr/b0YL8/2GO3xJEhInFmhKMUnEJQjZumK7KXGFhUy89PrsJWlakBVg==";
      };
    };
    "clean-css-4.2.3" = {
      name = "clean-css";
      packageName = "clean-css";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/clean-css/-/clean-css-4.2.3.tgz";
        sha512 = "VcMWDN54ZN/DS+g58HYL5/n4Zrqe8vHJpGA8KdgUXFU4fuP/aHNw8eld9SyEIyabIMJX/0RaY/fplOo5hYLSFA==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "commander-6.2.1" = {
      name = "commander";
      packageName = "commander";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-6.2.1.tgz";
        sha512 = "U7VdrJFnJgo4xjrHpTzu0yrHPGImdsmD95ZlgYSEajAn2JKzDhDTPG9kBTefmObL2w/ngeZnilk+OV9CG3d7UA==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "css-b64-images-0.2.5" = {
      name = "css-b64-images";
      packageName = "css-b64-images";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-b64-images/-/css-b64-images-0.2.5.tgz";
        sha1 = "42005d83204b2b4a5d93b6b1a5644133b5927a02";
      };
    };
    "d3-5.16.0" = {
      name = "d3";
      packageName = "d3";
      version = "5.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3/-/d3-5.16.0.tgz";
        sha512 = "4PL5hHaHwX4m7Zr1UapXW23apo6pexCgdetdJ5kTmADpG/7T9Gkxw0M0tf/pjoB63ezCCm0u5UaFYy2aMt0Mcw==";
      };
    };
    "d3-array-1.2.4" = {
      name = "d3-array";
      packageName = "d3-array";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-array/-/d3-array-1.2.4.tgz";
        sha512 = "KHW6M86R+FUPYGb3R5XiYjXPq7VzwxZ22buHhAEVG5ztoEcZZMLov530mmccaqA1GghZArjQV46fuc8kUqhhHw==";
      };
    };
    "d3-axis-1.0.12" = {
      name = "d3-axis";
      packageName = "d3-axis";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-axis/-/d3-axis-1.0.12.tgz";
        sha512 = "ejINPfPSNdGFKEOAtnBtdkpr24c4d4jsei6Lg98mxf424ivoDP2956/5HDpIAtmHo85lqT4pruy+zEgvRUBqaQ==";
      };
    };
    "d3-brush-1.1.6" = {
      name = "d3-brush";
      packageName = "d3-brush";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-brush/-/d3-brush-1.1.6.tgz";
        sha512 = "7RW+w7HfMCPyZLifTz/UnJmI5kdkXtpCbombUSs8xniAyo0vIbrDzDwUJB6eJOgl9u5DQOt2TQlYumxzD1SvYA==";
      };
    };
    "d3-chord-1.0.6" = {
      name = "d3-chord";
      packageName = "d3-chord";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-chord/-/d3-chord-1.0.6.tgz";
        sha512 = "JXA2Dro1Fxw9rJe33Uv+Ckr5IrAa74TlfDEhE/jfLOaXegMQFQTAgAw9WnZL8+HxVBRXaRGCkrNU7pJeylRIuA==";
      };
    };
    "d3-collection-1.0.7" = {
      name = "d3-collection";
      packageName = "d3-collection";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-collection/-/d3-collection-1.0.7.tgz";
        sha512 = "ii0/r5f4sjKNTfh84Di+DpztYwqKhEyUlKoPrzUFfeSkWxjW49xU2QzO9qrPrNkpdI0XJkfzvmTu8V2Zylln6A==";
      };
    };
    "d3-color-1.4.1" = {
      name = "d3-color";
      packageName = "d3-color";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-color/-/d3-color-1.4.1.tgz";
        sha512 = "p2sTHSLCJI2QKunbGb7ocOh7DgTAn8IrLx21QRc/BSnodXM4sv6aLQlnfpvehFMLZEfBc6g9pH9SWQccFYfJ9Q==";
      };
    };
    "d3-contour-1.3.2" = {
      name = "d3-contour";
      packageName = "d3-contour";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-contour/-/d3-contour-1.3.2.tgz";
        sha512 = "hoPp4K/rJCu0ladiH6zmJUEz6+u3lgR+GSm/QdM2BBvDraU39Vr7YdDCicJcxP1z8i9B/2dJLgDC1NcvlF8WCg==";
      };
    };
    "d3-dispatch-1.0.6" = {
      name = "d3-dispatch";
      packageName = "d3-dispatch";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-dispatch/-/d3-dispatch-1.0.6.tgz";
        sha512 = "fVjoElzjhCEy+Hbn8KygnmMS7Or0a9sI2UzGwoB7cCtvI1XpVN9GpoYlnb3xt2YV66oXYb1fLJ8GMvP4hdU1RA==";
      };
    };
    "d3-drag-1.2.5" = {
      name = "d3-drag";
      packageName = "d3-drag";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-drag/-/d3-drag-1.2.5.tgz";
        sha512 = "rD1ohlkKQwMZYkQlYVCrSFxsWPzI97+W+PaEIBNTMxRuxz9RF0Hi5nJWHGVJ3Om9d2fRTe1yOBINJyy/ahV95w==";
      };
    };
    "d3-dsv-1.2.0" = {
      name = "d3-dsv";
      packageName = "d3-dsv";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-dsv/-/d3-dsv-1.2.0.tgz";
        sha512 = "9yVlqvZcSOMhCYzniHE7EVUws7Fa1zgw+/EAV2BxJoG3ME19V6BQFBwI855XQDsxyOuG7NibqRMTtiF/Qup46g==";
      };
    };
    "d3-ease-1.0.7" = {
      name = "d3-ease";
      packageName = "d3-ease";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-ease/-/d3-ease-1.0.7.tgz";
        sha512 = "lx14ZPYkhNx0s/2HX5sLFUI3mbasHjSSpwO/KaaNACweVwxUruKyWVcb293wMv1RqTPZyZ8kSZ2NogUZNcLOFQ==";
      };
    };
    "d3-fetch-1.2.0" = {
      name = "d3-fetch";
      packageName = "d3-fetch";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-fetch/-/d3-fetch-1.2.0.tgz";
        sha512 = "yC78NBVcd2zFAyR/HnUiBS7Lf6inSCoWcSxFfw8FYL7ydiqe80SazNwoffcqOfs95XaLo7yebsmQqDKSsXUtvA==";
      };
    };
    "d3-force-1.2.1" = {
      name = "d3-force";
      packageName = "d3-force";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-force/-/d3-force-1.2.1.tgz";
        sha512 = "HHvehyaiUlVo5CxBJ0yF/xny4xoaxFxDnBXNvNcfW9adORGZfyNF1dj6DGLKyk4Yh3brP/1h3rnDzdIAwL08zg==";
      };
    };
    "d3-format-1.4.5" = {
      name = "d3-format";
      packageName = "d3-format";
      version = "1.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-format/-/d3-format-1.4.5.tgz";
        sha512 = "J0piedu6Z8iB6TbIGfZgDzfXxUFN3qQRMofy2oPdXzQibYGqPB/9iMcxr/TGalU+2RsyDO+U4f33id8tbnSRMQ==";
      };
    };
    "d3-geo-1.12.1" = {
      name = "d3-geo";
      packageName = "d3-geo";
      version = "1.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-geo/-/d3-geo-1.12.1.tgz";
        sha512 = "XG4d1c/UJSEX9NfU02KwBL6BYPj8YKHxgBEw5om2ZnTRSbIcego6dhHwcxuSR3clxh0EpE38os1DVPOmnYtTPg==";
      };
    };
    "d3-hierarchy-1.1.9" = {
      name = "d3-hierarchy";
      packageName = "d3-hierarchy";
      version = "1.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-hierarchy/-/d3-hierarchy-1.1.9.tgz";
        sha512 = "j8tPxlqh1srJHAtxfvOUwKNYJkQuBFdM1+JAUfq6xqH5eAqf93L7oG1NVqDa4CpFZNvnNKtCYEUC8KY9yEn9lQ==";
      };
    };
    "d3-interpolate-1.4.0" = {
      name = "d3-interpolate";
      packageName = "d3-interpolate";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-interpolate/-/d3-interpolate-1.4.0.tgz";
        sha512 = "V9znK0zc3jOPV4VD2zZn0sDhZU3WAE2bmlxdIwwQPPzPjvyLkd8B3JUVdS1IDUFDkWZ72c9qnv1GK2ZagTZ8EA==";
      };
    };
    "d3-path-1.0.9" = {
      name = "d3-path";
      packageName = "d3-path";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-path/-/d3-path-1.0.9.tgz";
        sha512 = "VLaYcn81dtHVTjEHd8B+pbe9yHWpXKZUC87PzoFmsFrJqgFwDe/qxfp5MlfsfM1V5E/iVt0MmEbWQ7FVIXh/bg==";
      };
    };
    "d3-polygon-1.0.6" = {
      name = "d3-polygon";
      packageName = "d3-polygon";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-polygon/-/d3-polygon-1.0.6.tgz";
        sha512 = "k+RF7WvI08PC8reEoXa/w2nSg5AUMTi+peBD9cmFc+0ixHfbs4QmxxkarVal1IkVkgxVuk9JSHhJURHiyHKAuQ==";
      };
    };
    "d3-quadtree-1.0.7" = {
      name = "d3-quadtree";
      packageName = "d3-quadtree";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-quadtree/-/d3-quadtree-1.0.7.tgz";
        sha512 = "RKPAeXnkC59IDGD0Wu5mANy0Q2V28L+fNe65pOCXVdVuTJS3WPKaJlFHer32Rbh9gIo9qMuJXio8ra4+YmIymA==";
      };
    };
    "d3-random-1.1.2" = {
      name = "d3-random";
      packageName = "d3-random";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-random/-/d3-random-1.1.2.tgz";
        sha512 = "6AK5BNpIFqP+cx/sreKzNjWbwZQCSUatxq+pPRmFIQaWuoD+NrbVWw7YWpHiXpCQ/NanKdtGDuB+VQcZDaEmYQ==";
      };
    };
    "d3-scale-2.2.2" = {
      name = "d3-scale";
      packageName = "d3-scale";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-scale/-/d3-scale-2.2.2.tgz";
        sha512 = "LbeEvGgIb8UMcAa0EATLNX0lelKWGYDQiPdHj+gLblGVhGLyNbaCn3EvrJf0A3Y/uOOU5aD6MTh5ZFCdEwGiCw==";
      };
    };
    "d3-scale-chromatic-1.5.0" = {
      name = "d3-scale-chromatic";
      packageName = "d3-scale-chromatic";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-scale-chromatic/-/d3-scale-chromatic-1.5.0.tgz";
        sha512 = "ACcL46DYImpRFMBcpk9HhtIyC7bTBR4fNOPxwVSl0LfulDAwyiHyPOTqcDG1+t5d4P9W7t/2NAuWu59aKko/cg==";
      };
    };
    "d3-selection-1.4.2" = {
      name = "d3-selection";
      packageName = "d3-selection";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-selection/-/d3-selection-1.4.2.tgz";
        sha512 = "SJ0BqYihzOjDnnlfyeHT0e30k0K1+5sR3d5fNueCNeuhZTnGw4M4o8mqJchSwgKMXCNFo+e2VTChiSJ0vYtXkg==";
      };
    };
    "d3-shape-1.3.7" = {
      name = "d3-shape";
      packageName = "d3-shape";
      version = "1.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-shape/-/d3-shape-1.3.7.tgz";
        sha512 = "EUkvKjqPFUAZyOlhY5gzCxCeI0Aep04LwIRpsZ/mLFelJiUfnK56jo5JMDSE7yyP2kLSb6LtF+S5chMk7uqPqw==";
      };
    };
    "d3-time-1.1.0" = {
      name = "d3-time";
      packageName = "d3-time";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-time/-/d3-time-1.1.0.tgz";
        sha512 = "Xh0isrZ5rPYYdqhAVk8VLnMEidhz5aP7htAADH6MfzgmmicPkTo8LhkLxci61/lCB7n7UmE3bN0leRt+qvkLxA==";
      };
    };
    "d3-time-format-2.3.0" = {
      name = "d3-time-format";
      packageName = "d3-time-format";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-time-format/-/d3-time-format-2.3.0.tgz";
        sha512 = "guv6b2H37s2Uq/GefleCDtbe0XZAuy7Wa49VGkPVPMfLL9qObgBST3lEHJBMUp8S7NdLQAGIvr2KXk8Hc98iKQ==";
      };
    };
    "d3-timer-1.0.10" = {
      name = "d3-timer";
      packageName = "d3-timer";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-timer/-/d3-timer-1.0.10.tgz";
        sha512 = "B1JDm0XDaQC+uvo4DT79H0XmBskgS3l6Ve+1SBCfxgmtIb1AVrPIoqd+nPSv+loMX8szQ0sVUhGngL7D5QPiXw==";
      };
    };
    "d3-transition-1.3.2" = {
      name = "d3-transition";
      packageName = "d3-transition";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-transition/-/d3-transition-1.3.2.tgz";
        sha512 = "sc0gRU4PFqZ47lPVHloMn9tlPcv8jxgOQg+0zjhfZXMQuvppjG6YuwdMBE0TuqCZjeJkLecku/l9R0JPcRhaDA==";
      };
    };
    "d3-voronoi-1.1.4" = {
      name = "d3-voronoi";
      packageName = "d3-voronoi";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-voronoi/-/d3-voronoi-1.1.4.tgz";
        sha512 = "dArJ32hchFsrQ8uMiTBLq256MpnZjeuBtdHpaDlYuQyjU0CVzCJl/BVW+SkszaAeH95D/8gxqAhgx0ouAWAfRg==";
      };
    };
    "d3-zoom-1.8.3" = {
      name = "d3-zoom";
      packageName = "d3-zoom";
      version = "1.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-zoom/-/d3-zoom-1.8.3.tgz";
        sha512 = "VoLXTK4wvy1a0JpH2Il+F2CiOhVu7VRXWF5M/LroMIh3/zBAC3WAt7QoIvPibOavVo20hN6/37vwAsdBejLyKQ==";
      };
    };
    "dagre-0.8.5" = {
      name = "dagre";
      packageName = "dagre";
      version = "0.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/dagre/-/dagre-0.8.5.tgz";
        sha512 = "/aTqmnRta7x7MCCpExk7HQL2O4owCT2h8NT//9I1OQ9vt29Pa0BzSAkR5lwFUcQ7491yVi/3CXU9jQ5o0Mn2Sw==";
      };
    };
    "dagre-d3-0.6.4" = {
      name = "dagre-d3";
      packageName = "dagre-d3";
      version = "0.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/dagre-d3/-/dagre-d3-0.6.4.tgz";
        sha512 = "e/6jXeCP7/ptlAM48clmX4xTZc5Ek6T6kagS7Oz2HrYSdqcLZFLqpAfh7ldbZRFfxCZVyh61NEPR08UQRVxJzQ==";
      };
    };
    "debug-4.3.2" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.2.tgz";
        sha512 = "mOp8wKcvj7XxC78zLgw/ZA+6TSgkoE2C/ienthhRD298T7UNwAg9diBpLRxC0mOezLl4B0xV7M0cCO6P/O0Xhw==";
      };
    };
    "devtools-protocol-0.0.854822" = {
      name = "devtools-protocol";
      packageName = "devtools-protocol";
      version = "0.0.854822";
      src = fetchurl {
        url = "https://registry.npmjs.org/devtools-protocol/-/devtools-protocol-0.0.854822.tgz";
        sha512 = "xd4D8kHQtB0KtWW0c9xBZD5LVtm9chkMOfs/3Yn01RhT/sFIsVtzTtypfKoFfWBaL+7xCYLxjOLkhwPXaX/Kcg==";
      };
    };
    "end-of-stream-1.4.4" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.4.tgz";
        sha512 = "+uw1inIHVPQoaVuHzRyXd21icM+cnt4CzD5rW+NC1wjOUSTOs+Te7FOv7AhN7vS9x/oIyhLP5PR1H+phQAHu5Q==";
      };
    };
    "entity-decode-2.0.2" = {
      name = "entity-decode";
      packageName = "entity-decode";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/entity-decode/-/entity-decode-2.0.2.tgz";
        sha512 = "5CCY/3ci4MC1m2jlumNjWd7VBFt4VfFnmSqSNmVcXq4gxM3Vmarxtt+SvmBnzwLS669MWdVuXboNVj1qN2esVg==";
      };
    };
    "extract-zip-2.0.1" = {
      name = "extract-zip";
      packageName = "extract-zip";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extract-zip/-/extract-zip-2.0.1.tgz";
        sha512 = "GDhU9ntwuKyGXdZBUgTIe+vXnWj0fppUEtMDL0+idd5Sta8TGpHssn/eusA9mrPr9qNDym6SxAYZjNvCn/9RBg==";
      };
    };
    "fd-slicer-1.1.0" = {
      name = "fd-slicer";
      packageName = "fd-slicer";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fd-slicer/-/fd-slicer-1.1.0.tgz";
        sha1 = "25c7c89cb1f9077f8891bbe61d8f390eae256f1e";
      };
    };
    "find-up-4.1.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-4.1.0.tgz";
        sha512 = "PpOwAdQ/YlXQ2vj8a3h8IipDuYRi3wceVQQGYWxNINccq40Anw7BlsEXCMbt1Zt+OLA6Fq9suIpIWD0OsnISlw==";
      };
    };
    "fs-constants-1.0.0" = {
      name = "fs-constants";
      packageName = "fs-constants";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-constants/-/fs-constants-1.0.0.tgz";
        sha512 = "y6OAwoSIf7FyjMIv94u+b5rdheZEjzR63GTyZJm5qh4Bi+2YgwLCcI/fPFZkL5PSixOt6ZNKm+w+Hfp/Bciwow==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "get-stream-5.2.0" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-5.2.0.tgz";
        sha512 = "nBF+F1rAZVCu/p7rjzgA+Yb4lfYXrpl7a6VmJrU8wF9I1CKvP/QwPNZHnOlwbTkY6dvtFIzFMSyQXbLoTQPRpA==";
      };
    };
    "glob-7.1.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.6.tgz";
        sha512 = "LwaxwyZ72Lk7vZINtNNrywX0ZuLyStrdDtabefZKAY5ZGJhVtgdznluResxNmPitE0SAO+O26sWTHeKSI2wMBA==";
      };
    };
    "graphlib-2.1.8" = {
      name = "graphlib";
      packageName = "graphlib";
      version = "2.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphlib/-/graphlib-2.1.8.tgz";
        sha512 = "jcLLfkpoVGmH7/InMC/1hIvOPSUh38oJtGhvrOFGzioE1DZ+0YW16RgmOJhHiuWTvGiJQ9Z1Ik43JvkRPRvE+A==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "he-1.2.0" = {
      name = "he";
      packageName = "he";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/he/-/he-1.2.0.tgz";
        sha512 = "F/1DnUGPopORZi0ni+CvrCgHQ5FyEAHRLSApuYWMmrbSwoN2Mn/7k+Gl38gJnR7yyDZk6WLXwiGod1JOWNDKGw==";
      };
    };
    "html-minifier-4.0.0" = {
      name = "html-minifier";
      packageName = "html-minifier";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/html-minifier/-/html-minifier-4.0.0.tgz";
        sha512 = "aoGxanpFPLg7MkIl/DDFYtb0iWz7jMFGqFhvEDZga6/4QTjneiD8I/NXL1x5aaoCp7FSIT6h/OhykDdPsbtMig==";
      };
    };
    "https-proxy-agent-5.0.0" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-5.0.0.tgz";
        sha512 = "EkYm5BcKUGiduxzSt3Eppko+PiNWNEpa4ySk9vTC6wDsQJW9rHSa+UhGNJoRYp7bz6Ht1eaRIa6QaJqO5rCFbA==";
      };
    };
    "iconv-lite-0.4.24" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz";
        sha512 = "v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "khroma-1.3.0" = {
      name = "khroma";
      packageName = "khroma";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/khroma/-/khroma-1.3.0.tgz";
        sha512 = "fpi0vIulP3FrM3BQOsEs+0ujWUNrg/YyHtEAcnvPxIHbASHNXEKEsDHtU2mADnJss7KvEdz7z2pUCQAEfFaFbA==";
      };
    };
    "locate-path-5.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-5.0.0.tgz";
        sha512 = "t7hw9pI+WvuwNJXwk5zVHpyhIqzg2qTlklJOf0mVxGSbe3Fp2VieZcduNYjaLDoy6p9uGpQEGWG87WpMKlNq8g==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lower-case-1.1.4" = {
      name = "lower-case";
      packageName = "lower-case";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lower-case/-/lower-case-1.1.4.tgz";
        sha1 = "9a2cabd1b9e8e0ae993a4bf7d5875c39c42e8eac";
      };
    };
    "mermaid-8.9.2" = {
      name = "mermaid";
      packageName = "mermaid";
      version = "8.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mermaid/-/mermaid-8.9.2.tgz";
        sha512 = "XWEaraDRDlHZexdeHSSr/MH4VJAOksRSPudchi69ecZJ7IUjjlzHsg32n4ZwJUh6lFO+NMYLHwHNNYUyxIjGPg==";
      };
    };
    "minify-4.1.3" = {
      name = "minify";
      packageName = "minify";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minify/-/minify-4.1.3.tgz";
        sha512 = "ykuscavxivSmVpcCzsXmsVTukWYLUUtPhHj0w2ILvHDGqC+hsuTCihBn9+PJBd58JNvWTNg9132J9nrrI2anzA==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "mkdirp-classic-0.5.3" = {
      name = "mkdirp-classic";
      packageName = "mkdirp-classic";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp-classic/-/mkdirp-classic-0.5.3.tgz";
        sha512 = "gKLcREMhtuZRwRAfqP3RFW+TK4JqApVBtOIftVgjuABpAtpxhPGaDcfvbhNvD0B8iD1oUr/txX35NjcaY6Ns/A==";
      };
    };
    "moment-mini-2.24.0" = {
      name = "moment-mini";
      packageName = "moment-mini";
      version = "2.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment-mini/-/moment-mini-2.24.0.tgz";
        sha512 = "9ARkWHBs+6YJIvrIp0Ik5tyTTtP9PoV0Ssu2Ocq5y9v8+NOOpWiRshAp8c4rZVWTOe+157on/5G+zj5pwIQFEQ==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "no-case-2.3.2" = {
      name = "no-case";
      packageName = "no-case";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/no-case/-/no-case-2.3.2.tgz";
        sha512 = "rmTZ9kz+f3rCvK2TD1Ue/oZlns7OGoIWP4fc3llxxRXlOkHKoWPPWJOfFYpITabSow43QJbRIoHQXtt10VldyQ==";
      };
    };
    "node-fetch-2.6.1" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.1.tgz";
        sha512 = "V4aYg89jEoVRxRb2fJdAg8FHvI7cEyYdVAh94HH0UIK8oJxUfkjlDQN9RbMx+bEjP7+ggMiFRprSti032Oipxw==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "p-limit-2.3.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-2.3.0.tgz";
        sha512 = "//88mFWSJx8lxCzwdAABTJL2MyWB12+eIY7MDL2SqLmAkeKU9qxRvWuSyTjm3FUmpBEMuFfckAIqEaVGUDxb6w==";
      };
    };
    "p-locate-4.1.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-4.1.0.tgz";
        sha512 = "R79ZZ/0wAxKGu3oYMlz8jy/kbhsNrS7SKZ7PxEHBgJ5+F2mtFW2fK2cOtBh1cHYkQsbzFV7I+EoRKe6Yt0oK7A==";
      };
    };
    "p-try-2.2.0" = {
      name = "p-try";
      packageName = "p-try";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-try/-/p-try-2.2.0.tgz";
        sha512 = "R4nPAVTAU0B9D35/Gk3uJf/7XYbQcyohSKdvAxIRSNghFl4e71hVoGnBNQz9cWaXxO2I10KTC+3jMdvvoKw6dQ==";
      };
    };
    "param-case-2.1.1" = {
      name = "param-case";
      packageName = "param-case";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/param-case/-/param-case-2.1.1.tgz";
        sha1 = "df94fd8cf6531ecf75e6bef9a0858fbc72be2247";
      };
    };
    "path-exists-4.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-4.0.0.tgz";
        sha512 = "ak9Qy5Q7jYb2Wwcey5Fpvg2KoAc/ZIhLSLOSBmRmygPsGwkVVt0fZa0qrtMz+m6tJTAHfZQ8FnmB4MG4LWy7/w==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "pend-1.2.0" = {
      name = "pend";
      packageName = "pend";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pend/-/pend-1.2.0.tgz";
        sha1 = "7a57eb550a6783f9115331fcf4663d5c8e007a50";
      };
    };
    "pkg-dir-4.2.0" = {
      name = "pkg-dir";
      packageName = "pkg-dir";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pkg-dir/-/pkg-dir-4.2.0.tgz";
        sha512 = "HRDzbaKjC+AOWVXxAU/x54COGeIv9eb+6CkDSQoNTt4XyWoIJvuPsXizxu/Fr23EiekbtZwmh1IcIG/l/a10GQ==";
      };
    };
    "progress-2.0.3" = {
      name = "progress";
      packageName = "progress";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/progress/-/progress-2.0.3.tgz";
        sha512 = "7PiHtLll5LdnKIMw100I+8xJXR5gW2QwWYkT6iJva0bXitZKa/XMrSbdmg3r2Xnaidz9Qumd0VPaMrZlF9V9sA==";
      };
    };
    "proxy-from-env-1.1.0" = {
      name = "proxy-from-env";
      packageName = "proxy-from-env";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-from-env/-/proxy-from-env-1.1.0.tgz";
        sha512 = "D+zkORCbA9f1tdWRK0RaCR3GPv50cMxcrz4X8k5LTSUD1Dkw47mKJEZQNunItRTkWwgtaUSo1RVFRIG9ZXiFYg==";
      };
    };
    "pump-3.0.0" = {
      name = "pump";
      packageName = "pump";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pump/-/pump-3.0.0.tgz";
        sha512 = "LwZy+p3SFs1Pytd/jYct4wpv49HiYCqd9Rlc5ZVdk0V+8Yzv6jR5Blk3TRmPL1ft69TxP0IMZGJ+WPFU2BFhww==";
      };
    };
    "puppeteer-8.0.0" = {
      name = "puppeteer";
      packageName = "puppeteer";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/puppeteer/-/puppeteer-8.0.0.tgz";
        sha512 = "D0RzSWlepeWkxPPdK3xhTcefj8rjah1791GE82Pdjsri49sy11ci/JQsAO8K2NRukqvwEtcI+ImP5F4ZiMvtIQ==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "relateurl-0.2.7" = {
      name = "relateurl";
      packageName = "relateurl";
      version = "0.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/relateurl/-/relateurl-0.2.7.tgz";
        sha1 = "54dbf377e51440aca90a4cd274600d3ff2d888a9";
      };
    };
    "rimraf-3.0.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz";
        sha512 = "JZkJMZkAGFFPP2YqXZXPbMlMBgsxzE8ILs4lMIX/2o0L9UBw9O/Y3o6wFw/i9YLapcUJWwqbi3kdxIPdC62TIA==";
      };
    };
    "rw-1.3.3" = {
      name = "rw";
      packageName = "rw";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/rw/-/rw-1.3.3.tgz";
        sha1 = "3f862dfa91ab766b14885ef4d01124bfda074fb4";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-support-0.5.19" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.5.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.19.tgz";
        sha512 = "Wonm7zOCIJzBGQdB+thsPar0kYuCIzYvxZwlBa87yi/Mdjv7Tip2cyVbLj5o0cFPN4EVkuTwb3GDDyUx2DGnGw==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "stylis-3.5.4" = {
      name = "stylis";
      packageName = "stylis";
      version = "3.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylis/-/stylis-3.5.4.tgz";
        sha512 = "8/3pSmthWM7lsPBKv7NXkzn2Uc9W7NotcwGNpJaa3k7WMM1XDCA4MgT5k/8BIexd5ydZdboXtU90XH9Ec4Bv/Q==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "tar-fs-2.1.1" = {
      name = "tar-fs";
      packageName = "tar-fs";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar-fs/-/tar-fs-2.1.1.tgz";
        sha512 = "V0r2Y9scmbDRLCNex/+hYzvp/zyYjvFbHPNgVTKfQvVrb6guiE/fxP+XblDNR011utopbkex2nM4dHNV6GDsng==";
      };
    };
    "tar-stream-2.2.0" = {
      name = "tar-stream";
      packageName = "tar-stream";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar-stream/-/tar-stream-2.2.0.tgz";
        sha512 = "ujeqbceABgwMZxEJnk2HDY2DlnUZ+9oEcb1KzTVfYHio0UE6dG71n60d8D2I4qNvleWrrXpmjpt7vZeF1LnMZQ==";
      };
    };
    "terser-4.8.0" = {
      name = "terser";
      packageName = "terser";
      version = "4.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/terser/-/terser-4.8.0.tgz";
        sha512 = "EAPipTNeWsb/3wLPeup1tVPaXfIaU68xMnVdPafIL1TV05OhASArYyIfFvnvJCNrR2NIOvDVNNTFRa+Re2MWyw==";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "try-catch-2.0.1" = {
      name = "try-catch";
      packageName = "try-catch";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/try-catch/-/try-catch-2.0.1.tgz";
        sha512 = "LsOrmObN/2WdM+y2xG+t16vhYrQsnV8wftXIcIOWZhQcBJvKGYuamJGwnU98A7Jxs2oZNkJztXlphEOoA0DWqg==";
      };
    };
    "try-to-catch-1.1.1" = {
      name = "try-to-catch";
      packageName = "try-to-catch";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/try-to-catch/-/try-to-catch-1.1.1.tgz";
        sha512 = "ikUlS+/BcImLhNYyIgZcEmq4byc31QpC+46/6Jm5ECWkVFhf8SM2Fp/0pMVXPX6vk45SMCwrP4Taxucne8I0VA==";
      };
    };
    "uglify-js-3.13.3" = {
      name = "uglify-js";
      packageName = "uglify-js";
      version = "3.13.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-js/-/uglify-js-3.13.3.tgz";
        sha512 = "otIc7O9LyxpUcQoXzj2hL4LPWKklO6LJWoJUzNa8A17Xgi4fOeDC8FBDOLHnC/Slo1CQgsZMcM6as0M76BZaig==";
      };
    };
    "unbzip2-stream-1.4.3" = {
      name = "unbzip2-stream";
      packageName = "unbzip2-stream";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/unbzip2-stream/-/unbzip2-stream-1.4.3.tgz";
        sha512 = "mlExGW4w71ebDJviH16lQLtZS32VKqsSfk80GCfUlwT/4/hNRFsoscrF/c++9xinkMzECL1uL9DDwXqFWkruPg==";
      };
    };
    "upper-case-1.1.3" = {
      name = "upper-case";
      packageName = "upper-case";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/upper-case/-/upper-case-1.1.3.tgz";
        sha1 = "f6b4501c2ec4cdd26ba78be7222961de77621598";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "ws-7.4.4" = {
      name = "ws";
      packageName = "ws";
      version = "7.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.4.4.tgz";
        sha512 = "Qm8k8ojNQIMx7S+Zp8u/uHOx7Qazv3Yv4q68MiWWWOJhiwG5W3x7iqmRtJo8xxrciZUY4vRxUTJCKuRnF28ZZw==";
      };
    };
    "yauzl-2.10.0" = {
      name = "yauzl";
      packageName = "yauzl";
      version = "2.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yauzl/-/yauzl-2.10.0.tgz";
        sha1 = "c7eb17c93e112cb1086fa6d8e51fb0667b79a5f9";
      };
    };
  };
  args = {
    name = "_at_mermaid-js_slash_mermaid-cli";
    packageName = "@mermaid-js/mermaid-cli";
    version = "8.9.2";
    # src = fetchFromGitHub {
    #   owner = "mermaid-js";
    #   repo = "mermaid-cli";
    #   rev = "8.9.2";
    #   sha256 = "1n03ymp1ndcbkb780p2s1b3n5b2i6j2mvr6j4zr9zxzqr7c9gp2s";
    # };
    src = gitignoreSource [".git"] ./source;
    dependencies = [
      sources."@braintree/sanitize-url-3.1.0"
      sources."@types/node-14.14.37"
      sources."@types/yauzl-2.9.1"
      sources."agent-base-6.0.2"
      sources."ansi-styles-4.3.0"
      sources."balanced-match-1.0.0"
      sources."base64-js-1.5.1"
      sources."bl-4.1.0"
      sources."brace-expansion-1.1.11"
      sources."buffer-5.7.1"
      sources."buffer-crc32-0.2.13"
      sources."buffer-from-1.1.1"
      sources."camel-case-3.0.0"
      sources."chalk-4.1.0"
      sources."chownr-1.1.4"
      sources."clean-css-4.2.3"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."commander-6.2.1"
      sources."concat-map-0.0.1"
      sources."css-b64-images-0.2.5"
      sources."d3-5.16.0"
      sources."d3-array-1.2.4"
      sources."d3-axis-1.0.12"
      sources."d3-brush-1.1.6"
      sources."d3-chord-1.0.6"
      sources."d3-collection-1.0.7"
      sources."d3-color-1.4.1"
      sources."d3-contour-1.3.2"
      sources."d3-dispatch-1.0.6"
      sources."d3-drag-1.2.5"
      (sources."d3-dsv-1.2.0" // {
        dependencies = [
          sources."commander-2.20.3"
        ];
      })
      sources."d3-ease-1.0.7"
      sources."d3-fetch-1.2.0"
      sources."d3-force-1.2.1"
      sources."d3-format-1.4.5"
      sources."d3-geo-1.12.1"
      sources."d3-hierarchy-1.1.9"
      sources."d3-interpolate-1.4.0"
      sources."d3-path-1.0.9"
      sources."d3-polygon-1.0.6"
      sources."d3-quadtree-1.0.7"
      sources."d3-random-1.1.2"
      sources."d3-scale-2.2.2"
      sources."d3-scale-chromatic-1.5.0"
      sources."d3-selection-1.4.2"
      sources."d3-shape-1.3.7"
      sources."d3-time-1.1.0"
      sources."d3-time-format-2.3.0"
      sources."d3-timer-1.0.10"
      sources."d3-transition-1.3.2"
      sources."d3-voronoi-1.1.4"
      sources."d3-zoom-1.8.3"
      sources."dagre-0.8.5"
      sources."dagre-d3-0.6.4"
      sources."debug-4.3.2"
      sources."devtools-protocol-0.0.854822"
      sources."end-of-stream-1.4.4"
      sources."entity-decode-2.0.2"
      sources."extract-zip-2.0.1"
      sources."fd-slicer-1.1.0"
      sources."find-up-4.1.0"
      sources."fs-constants-1.0.0"
      sources."fs.realpath-1.0.0"
      sources."get-stream-5.2.0"
      sources."glob-7.1.6"
      sources."graphlib-2.1.8"
      sources."has-flag-4.0.0"
      sources."he-1.2.0"
      (sources."html-minifier-4.0.0" // {
        dependencies = [
          sources."commander-2.20.3"
        ];
      })
      sources."https-proxy-agent-5.0.0"
      sources."iconv-lite-0.4.24"
      sources."ieee754-1.2.1"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."khroma-1.3.0"
      sources."locate-path-5.0.0"
      sources."lodash-4.17.21"
      sources."lower-case-1.1.4"
      sources."mermaid-8.9.2"
      sources."minify-4.1.3"
      sources."minimatch-3.0.4"
      sources."mkdirp-classic-0.5.3"
      sources."moment-mini-2.24.0"
      sources."ms-2.1.2"
      sources."no-case-2.3.2"
      sources."node-fetch-2.6.1"
      sources."once-1.4.0"
      sources."p-limit-2.3.0"
      sources."p-locate-4.1.0"
      sources."p-try-2.2.0"
      sources."param-case-2.1.1"
      sources."path-exists-4.0.0"
      sources."path-is-absolute-1.0.1"
      sources."pend-1.2.0"
      sources."pkg-dir-4.2.0"
      sources."progress-2.0.3"
      sources."proxy-from-env-1.1.0"
      sources."pump-3.0.0"
      sources."puppeteer-8.0.0"
      sources."readable-stream-3.6.0"
      sources."relateurl-0.2.7"
      sources."rimraf-3.0.2"
      sources."rw-1.3.3"
      sources."safe-buffer-5.2.1"
      sources."safer-buffer-2.1.2"
      sources."source-map-0.6.1"
      sources."source-map-support-0.5.19"
      sources."string_decoder-1.3.0"
      sources."stylis-3.5.4"
      sources."supports-color-7.2.0"
      sources."tar-fs-2.1.1"
      sources."tar-stream-2.2.0"
      (sources."terser-4.8.0" // {
        dependencies = [
          sources."commander-2.20.3"
        ];
      })
      sources."through-2.3.8"
      sources."try-catch-2.0.1"
      sources."try-to-catch-1.1.1"
      sources."uglify-js-3.13.3"
      sources."unbzip2-stream-1.4.3"
      sources."upper-case-1.1.3"
      sources."util-deprecate-1.0.2"
      sources."wrappy-1.0.2"
      sources."ws-7.4.4"
      sources."yauzl-2.10.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Command-line interface for mermaid";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
